### ISSUE TITLE
calibration matrix rectification after image padding

### ISSUE THREAD

**Issue by Jasonkks** [zhiqi-li/BEVFormer#103]
Hi authors, thanks for the great work! 

I notice there seems to be no calibration matrix rectification after the image padding process, in which the image shape is actually changed (padded to be multiples of 32 for example). Isn't this going to cause misalignment in 3D to 2D image projection? 

Thank you.

**Comment by zhiqi-li** [comment]
The padding is added to the right and bottom of the image, and the lidar2img matrix is not affected by this. The 3D point (x,y,z) still projects on the (X, Y) on the 2D image, with or without padding.  But when judging whether the projected point is within the image, using the image shape before padding is better.

**Comment by Jasonkks** [comment]
Thanks a lot for the reply!
