### ISSUE TITLE
'nuscenes_infos_train.pkl' not found

### ISSUE THREAD

**Issue by junlee618** [zhiqi-li/BEVFormer#15]
I met 'nuscenes_infos_train.pkl not found' problem when creating data.

I workaround by copying following 4 files from somewhere else.
(nuscenes_infos_train.pkl
nuscenes_infos_train_mono3d.coco.json
nuscenes_infos_val.pkl
nuscenes_infos_val_mono3d.coco.json)

Is it a bug? or do I miss something?

**Comment by zhiqi-li** [comment]
See https://github.com/zhiqi-li/BEVFormer/blob/master/docs/prepare_dataset.md.
We use our custom anns files.

**Comment by junlee618** [comment]
I use the following command to create data:
 python -u tools/create_data.py nuscenes --version v1.0 --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes

and got the error:
FileNotFoundError: NuScenesDataset: [Errno 2] No such file or directory: './data/nuscenes/nuscenes_infos_train.pkl'

Does it miss the " temporal" in the last code line?

   else:
        info_train_path = osp.join(
            out_dir, f'{info_prefix}_infos_temporal_train.pkl')
        info_val_path = osp.join(
            out_dir, f'{info_prefix}_infos_temporal_val.pkl')
        nuscenes_converter.export_2d_annotation(
            root_path, info_train_path, version=version)
        nuscenes_converter.export_2d_annotation(
            root_path, info_val_path, version=version)
        create_groundtruth_database(dataset_name, root_path, info_prefix,
                                    f'{out_dir}/{info_prefix}_infos_train.pkl')

**Comment by zhiqi-li** [comment]
Sorry for that, I removed this line `create_groundtruth_database(dataset_name, root_path, info_prefix,
f'{out_dir}/{info_prefix}_infos_train.pkl')`  because the generated files are not used.

**Comment by junlee618** [comment]
Many thanks!
Create data successful on mini dataset(with can_bus also added). 
Now trying on full dataset…

**Comment by oneway3124** [comment]
@junlee618 How do you create the pkl files on mini dataset?
Thanks!

**Comment by junlee618** [comment]
sorry for late, I use the following command:
python -u tools/create_data.py nuscenes --version v1.0-mini --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes

**Comment by leslieburke** [comment]
@junlee618 
i tried to follow your method to create pkl file，but i got：

python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini
Traceback (most recent call last):
  File "tools/create_data.py", line 10, in <module>
    from data_converter import indoor_converter as indoor
  File "/home/cidi/zcl/project/BEVFormer/tools/data_converter/indoor_converter.py", line 6, in <module>
    from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
ModuleNotFoundError: No module named 'tools.data_converter'

do you know why？

**Comment by ZitaoWang97** [comment]
@leslieburke  same problem. Have you already resolved the path issue?

**Comment by leslieburke** [comment]
> @leslieburke same problem. Have you already resolved the path issue?

change the code
from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
to 
from .s3dis_data_utils import S3DISData, S3DISSegData

**Comment by TurtleWithA100** [comment]
> > @leslieburke same problem. Have you already resolved the path issue?
> 
> change the code from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData to from .s3dis_data_utils import S3DISData, S3DISSegData

No need to change the code, you can execute `export PYTHONPATH="/path/to/BEVFormer/tools:$PYTHONPATH"`, this works for me.

**Comment by lix19937** [comment]
see https://github.com/fundamentalvision/BEVFormer/pull/241#issuecomment-2049094853
