### ISSUE TITLE
CustomNuScenesDataset register fail

### ISSUE THREAD

**Issue by junlee618** [zhiqi-li/BEVFormer#17]
when runing the test on windows environment, I got this error:

test.py", line 195, in main
    dataset = build_dataset(cfg.data.test)

KeyError: 'CustomNuScenesDataset is not in the dataset registry'

looks like this module fail to register. 
any idea how to debug this?
(on linux it has no such problem and can successfully run the inference)

**Comment by zhiqi-li** [comment]
Line 114-135 import custom modules based on plugin path, but the path format used here is linux-specific.

**Comment by junlee618** [comment]
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "E:/workspace/BEVFormer-master/tools/test.py", line 262, in <module>
    main()
  File "E:/workspace/BEVFormer-master/tools/test.py", line 192, in main
    dataset = build_dataset(cfg.data.test)
  File "e:\ai_tools\mmdetection3d-master\mmdet3d\datasets\builder.py", line 43, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Program Files\Python37\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CustomNuScenesDataset is not in the dataset registry'

**Comment by junlee618** [comment]
above is the full log, it seems not related to the path, because it prints the module path(see the first line of the log) normally

**Comment by junlee618** [comment]
Looks like the key to this problem is the registry's scope.
I fix this error (under windows system) by registering the CustomNuScenesDataset under 'mmdet3d' scope, instead of 'mmdet' scope, like following:

file: projects/mmdet3d_plugin/datasets/nuscenes_dataset.py
-from mmdet.datasets import DATASETS
+from mmdet3d.datasets import DATASETS

Maybe it relates to the mm packages' version combination

linux
mmcv-full               1.4.5
mmdet                   2.20.0
mmdet3d                 0.18.0
mmsegmentation          0.20.2


windows
mmcv-full               1.5.0
mmdet                   2.19.0
mmdet3d                 1.0.0rc2
mmsegmentation          0.24.1

**Comment by zhiqi-li** [comment]
mmdet3d>=1.0 may not work properly. Compared to the previous version, the compatibilities of models are broken due to the unification and simplification of coordinate systems.

**Comment by junlee618** [comment]
Got it! Thanks to the important information! 
I'll reset my windows environment~
