### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by adrianfyh** [zhiqi-li/BEVFormer#18]
Hello ,

After installation and data preparation, if just wanna use the pre-trained .pth to see the amazing model, is it possible to do the visualization with nuscense v1.0-mini? If yes, how?

Thank you very much.

**Comment by zhiqi-li** [comment]
`./tools/dist_test.sh ./projects/configs/bevformer/base.py path/to/bevformer_r101_dcn_24ep.pth 8`

**Comment by zhiqi-li** [comment]
More details can be provided?

**Comment by zhiqi-li** [comment]
> > More details can be provided?
> 
> ah, sorry. i just found that there is "RuntimeError: CUDA out of memory" my apologize

It requires around 7500M GPU memory.

**Comment by jian-6666** [comment]
> ./tools/dist_test.sh

hi, i also got the same issue, it appeared the same problem as this screenshot. but it is not the memory problem. have you already solved the problem? :)
