### ISSUE TITLE
1 GPU training

### ISSUE THREAD

**Issue by chen-cvresearch** [zhiqi-li/BEVFormer#19]
hello, I used only 1 GPU to train, face with Error: 
TypeError: can't pickle dict_keys objects
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2943) of binary: /usr/bin/python3

**Comment by chen-cvresearch** [comment]
change dist_train.sh  : python $(dirname "$0")/train.py $CONFIG   solved my problem

**Comment by Rango-T10000** [comment]
> change dist_train.sh : python $(dirname "$0")/train.py $CONFIG solved my problem

Hello, I met the same problem.
TypeError: FormatCode() got an unexpected keyword argument 'verify'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) 

Hoe can you change the code in dist_train.sh?
Can you tell me what is changed?
