### ISSUE TITLE
batch size setting

### ISSUE THREAD

**Issue by chen-cvresearch** [zhiqi-li/BEVFormer#20]
Hello, I want to know how to change the batch size. I meet with the CUDA out of memory when I use 1 GPU for training.

**Comment by zhiqi-li** [comment]
By default, our batch size is 1. With current setting, BEVFormer consumes around 25000M GPU memory.

**Comment by Bosszhe** [comment]
I changed the config parameter `samples_per_gpu=2`, but met this error.
How can I solve it?

> RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

![image](https://user-images.githubusercontent.com/34713622/174223670-2636b51b-e7d3-4408-8133-ed561cf486b7.png)
