### ISSUE TITLE
请问能在nuscenes 的min数据集合上进行测试吗？

### ISSUE THREAD

**Issue by scuizhibin** [zhiqi-li/BEVFormer#22]

**Comment by zhiqi-li** [comment]
Yes, the NDS and mAP on nuScenes-mini are 41.0 and 35.7.

**Comment by zhiqi-li** [comment]
mini数据集太小了，不能让模型正常收敛，mini一般用来验证整个训练流程中是否有问题。

**Comment by scuizhibin** [comment]
谢谢


---原始邮件---
发件人: &quot;Zhiqi ***@***.***&gt;
发送时间: 2022年6月15日(周三) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhiqi-li/BEVFormer] 请问能在nuscenes 的min数据集合上进行测试吗？ (Issue #22)




 
mini数据集太小了，不能让模型正常收敛，mini一般用来验证整个训练流程中是否有问题。
 
&mdash;
