### ISSUE TITLE
can not reimplement nds

### ISSUE THREAD

**Issue by LovPe** [zhiqi-li/BEVFormer#24]
I run test follow projects/BEVFormer/docs/getting_started.md . got result like this:
```text
Saving metrics to: test/bevformer_base/Wed_Jun_15_23_27_40_2022/pts_bbox
mAP: 0.4166
mATE: 0.6725
mASE: 0.7089
mAOE: 1.5625
mAVE: 0.3936
mAAE: 0.1975
NDS: 0.4110
Eval time: 218.7s
```
The mAP looks good. but the NDS is extremely low.
Any ideas why this?

**Comment by zhiqi-li** [comment]
Do you use mmdet3d>=1.0 to generate annotation files?

**Comment by LovPe** [comment]
I see... My mmdet3d comes from master version. 
![image](https://user-images.githubusercontent.com/11580882/173987371-5e6d129f-ce30-4b8d-b29a-0f9cd6806d29.png)
By the way, do you known what the main difference between 1.0 and old 0.x version? Thanks a lot

**Comment by zhiqi-li** [comment]
After mmdet3d V1.0: "The compatibilities of models are broken due to the unification and simplification of coordinate systems."

**Comment by LovPe** [comment]
great thanks
