### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by jian-6666** [zhiqi-li/BEVFormer#27]
hi,zhiqi, i wish you all the best. when i use the pre_trained model in v1.0-mini dataset, i got this error:
**torch.distributed.elastic.multiprocessing.errors.ChildFailedError:**
and i do not know how to fix it. could you please explain a little bit? i use 1 gpu, command is 
**./tools/dist_test.sh ./projects/configs/bevformer/bevformer_base.py ckpts/r101_dcn_fcos3d_pretrain.pth 1** : )

**Comment by jian-6666** [comment]
by the way, i just would like to see the amazing visulization of bevformer, but it did not work,could you please explain the steps of how to apply your beautiful model on the v1.0-mini dataset? :)

**Comment by zhiqi-li** [comment]
Did you follow this [Step-by-step installation instructions](https://github.com/zhiqi-li/BEVFormer/blob/master/docs/install.md) to install your env? It seems that this error has nothing to do with  BEVformer.

**Comment by jian-6666** [comment]
> It seems that this error has nothing to do with BEVformer.

hi,zhiqi, oh,yes, i followed every steps of the installations, well i think the env is ok, every steps of installations went well.  now it can read all the mini-dataset, but breakdown and give this info. :) thanks for the answering.

**Comment by zhiqi-li** [comment]
Dose your mmdet3d works？You can try some models in mmdet3d to verify it.

**Comment by leslieburke** [comment]
我也是，请问解决了吗

**Comment by leslieburke** [comment]
@WeiJunREN 请问解决了吗

**Comment by sainttelant** [comment]
i have the same issues when i evaluate the mini datasets in rtx3090, so how to solve this issues, please share the ideas, thanks a lot

**Comment by LadissonLai** [comment]
same problem.

**Comment by SizheWei** [comment]
I met this problem, too. I think my env is good, and my system is v100, 32GB. Is there anyone who fix this issue or have some ideas? Much appreciate!

**Comment by SizheWei** [comment]
> > It seems that this error has nothing to do with BEVformer.
> 
> hi,zhiqi, oh,yes, i followed every steps of the installations, well i think the env is ok, every steps of installations went well. now it can read all the mini-dataset, but breakdown and give this info. :) thanks for the answering.

and hi, jian-6666, have you solved it? thx! 😊

**Comment by SizheWei** [comment]
> > It seems that this error has nothing to do with BEVformer.
> 
> hi,zhiqi, oh,yes, i followed every steps of the installations, well i think the env is ok, every steps of installations went well. now it can read all the mini-dataset, but breakdown and give this info. :) thanks for the answering.

and hi @jian-6666 , have you solved it? thx!
