### ISSUE TITLE
about projection of Qp in BEV onto a small feature map

### ISSUE THREAD

**Issue by MasatoSaeki** [zhiqi-li/BEVFormer#28]
Thank you for your working.

What method are you using when projecting query Qp in BEV onto the small feature map obtained by FPN?

Intuitively, I don't think that can project that  with a 3x4 projection matrix because the small feature map does not have the location information of the original image.

**Comment by MasatoSaeki** [comment]
https://github.com/zhiqi-li/BEVFormer/blob/master/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L92
I think that this function did not take into account small feature maps.

**Comment by zhiqi-li** [comment]
We use relative position to get the features of  projected point

**Comment by MasatoSaeki** [comment]
Thank you for your replying.

How is the relative position determined with respect to the original image?

**Comment by zhiqi-li** [comment]
https://github.com/zhiqi-li/BEVFormer/blob/master/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L129
```
        reference_points_cam[..., 0] /= img_metas[0]['img_shape'][0][1]
        reference_points_cam[..., 1] /= img_metas[0]['img_shape'][0][0]
```
The reference points are normalized to 0-1

**Comment by MasatoSaeki** [comment]
I understand.

After this, you execute attention near the hit area.
(Please tell me if I'm wrong.)

Thank you very much.
