### ISSUE TITLE
The memory of BEVFormer-base

### ISSUE THREAD

**Issue by SuperHenry2333** [zhiqi-li/BEVFormer#30]
Dear authors, thanks for your great work! You show in the table that BEVFormer-base's memory is 28000M, but the log shows 18000M. Is this a typo? And when I run the code, the memory is 24400M.

**Comment by zhiqi-li** [comment]
The content of our Log is printed from the original code. During the experiment, we used fp16, which will only save GPU memory without affecting performance. Our open source code has undergone some slight modifications and uses fp32 by default. , but the model structure is the same as the original one. The ~28000M GPU memory required by the existing model is obtained from `nvidia-smi`.

**Comment by SuperHenry2333** [comment]
Thank you for your answer! You solved my problem.
