### ISSUE TITLE
waymo dataset evaluation

### ISSUE THREAD

**Issue by ZLTJohn** [zhiqi-li/BEVFormer#34]
Hello, thank you for sharing the code! I read your paper and check the code. It is really amazing that it achieve such great results both on nuscene and waymo dataset. 
Currently there is only code for nuscene dataset, and I wonder if you can provide configs and plugins for waymo dataset, so that I can reproduce the result on it ?

**Comment by hli2020** [comment]
> Hello, thank you for sharing the code! I read your paper and check the code. It is really amazing that it achieve such great results both on nuscene and waymo dataset. Currently there is only code for nuscene dataset, and I wonder if you can provide configs and plugins for waymo dataset, so that I can reproduce the result on it ?

Hi, there is no plan to release Waymo evaluation/dataloader for current version of BEVFormer.
We plan to do so in a latter release based on BEVFormer++ **around September**.
