### ISSUE TITLE
How can I visualize the val result？

### ISSUE THREAD

**Issue by Hoyyyaard** [zhiqi-li/BEVFormer#43]

**Comment by love-lost-found** [comment]
you can use this script https://github.com/zhiqi-li/BEVFormer/blob/master/tools/analysis_tools/visual.py.
First of all, you need to use the `test.sh` to generate the results files, then you can use this script to generate visualization results.

**Comment by nikhil-nakhate** [comment]
Could you share the link to the tool to generate the BEV result?
