### ISSUE TITLE
 undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by hygxy** [zhiqi-li/BEVFormer#44]
I followed exactly the same installation steps as described [here](https://github.com/zhiqi-li/BEVFormer/blob/master/docs/install.md), but when I run ```python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data```, i get the following error: ```undefined symbol: _ZNK2at6Tensor6deviceEv```.  My cuda version is 11.4 and driver version is 470.129.06

**Comment by zhiqi-li** [comment]
This is caused by the incorrect installation of Mmdet3d, most likely because of the version of gcc.

**Comment by hygxy** [comment]
> This is caused by the incorrect installation of Mmdet3d, most likely because of the conflicts of gcc version.

But I already execute this line:```conda install -c omgarcia gcc-6 # gcc-6.2``` as mentioned in the docus, what else should/can I try?

**Comment by zhiqi-li** [comment]
It may be necessary to compile and install mmcv and mmdet3d, and use the same gcc version when compiling.

**Comment by zhiqi-li** [comment]
> > 
> 
> Thx, I downgrade my Cuda version to 11.0 and now it works. I have though another question about the nuscenes datasets. The docus says `Download nuScenes V1.0 full dataset`. Does it mean that I need to download the mini(3.88 GB), all 10 parts of the trainval(around >300G in total) and the test(53.63 GB) dataset?

yeah, the full nuScenes is around 300G +.
