### ISSUE TITLE
请问在哪里设置训练batch_size

### ISSUE THREAD

**Issue by lvxuanxuan123** [zhiqi-li/BEVFormer#48]

**Comment by zhiqi-li** [comment]
The `samples_per_gpu` is the batch_size on per GPU. When adjusting the batch size, please adjust the learning rate accordingly.
https://github.com/zhiqi-li/BEVFormer/blob/846fb5bcf0ff746f4f50dfa436c7ccbf7e3122bd/projects/configs/bevformer_fp16/bevformer_tiny_fp16.py#L211

**Comment by lvxuanxuan123** [comment]
the issue has been solved
