### ISSUE TITLE
Are the multi-camera features multi-scale (output of FPN) or single scale (output of ResNet, stride=32) ?

### ISSUE THREAD

**Issue by zhanghengdev** [zhiqi-li/BEVFormer#5]
Hello, I'm wondering if  the multi-camera features are multi-scale (output of FPN) or single scale (output of ResNet, stride=32) ?
If they are not multi-scale, why not ?

**Comment by zhiqi-li** [comment]
Camera features are multi-scale (8s, 16s, 32s, and 64s).

**Comment by zhanghengdev** [comment]
Thank you for your response! But when project the 3D points into 2D feature coordinates, how to decide which layer of pyramid to use?

**Comment by zhiqi-li** [comment]
> Thank you for your response! But after project the 3D points into 2D feature coordinates (reference points), how to decide which layer of feature pyramid to use?

Similar to Deformable DETR, we use all feature layers.

**Comment by zhanghengdev** [comment]
Thank you for your response, it's clear to me now!
