### ISSUE TITLE
nuscenes数据集有10个压缩包，每个压缩包包含85个场景，请问假如我只想训练前两个压缩包，该怎么处理数据集v1.0trainval?

### ISSUE THREAD

**Issue by lvxuanxuan123** [zhiqi-li/BEVFormer#54]

**Comment by zhiqi-li** [comment]
如果你只是想要跑通整个模型，可以使用nuscnes-mini 替代nuscene. 但是如果只是想训练前两个压缩包的话，可以通过修改data convert 来生成只包含前两个压缩包数据的json.

**Comment by lvxuanxuan123** [comment]
> 如果你只是想要跑通整个模型，可以使用nuscnes-mini 替代nuscene. 但是如果只是想训练前两个压缩包的话，可以通过修改data convert 来生成只包含前两个压缩包数据的json.

请问data convert文件在哪里
