### ISSUE TITLE
Training time and Volatile GPU-Util

### ISSUE THREAD

**Issue by annopackage** [zhiqi-li/BEVFormer#65]
Hi, thanks for your great work. While training using default data loading and transformation methods, volatile gpu-util is low(around 50%) maybe due to loading multi images each batch, and the time cost bottleneck is in mmcv.imread or resize. I wonder if there is any technique to improve GPU utilization rate except using more num workers?

**Comment by zhiqi-li** [comment]
Maybe you can load the images into memory in advance to reduce the IO time.
