### ISSUE TITLE
检测出的车分布在两个摄像头是会认为同一个吗

### ISSUE THREAD

**Issue by bobd988** [zhiqi-li/BEVFormer#67]
检测出的车尾在左前摄像头，车头在中间摄像头，有什么办法知道是同一个物体？

另外bev 的图怎么看输出？  目前运行visual.py 只输出摄像头检测结果。

**Comment by zhiqi-li** [comment]
多个摄像头感知到的相同内容在BEV空间下是一致的，visual.py应该会同时输出图像和BEV视角下的检测结果。
