### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by ShangWeize** [zhiqi-li/BEVFormer#68]
您好，请问有nusences数据集预处理的文件可以分享么？
nuscenes_infos_temporal_val.pkl
nuscenes_infos_temporal_train.pkl

**Comment by zhiqi-li** [comment]
可以通过脚本生成对应的文件https://github.com/zhiqi-li/BEVFormer/blob/master/docs/prepare_dataset.md

**Comment by ShangWeize** [comment]
我也在用这个脚本生成，但是时间太长了，要十几个小时，所以想问问有没有可以共享的

**Comment by ShangWeize** [comment]
您好，我这边生成pkl之后，在使用的时候出现了这样一个问题：
我的数据集是在云端的，pkl也在云端，生成pkl的时候我是按照的本地的目录生成的pkl,然后在另外一台服务器上，加载数据集的时候，我明明已经将data_root修改成对应服务器的目录,但是加载的时候，还是会读取我最开始生成的pkl对应的目录，结果就是显示目录不存在，无法读取。
在文件create_data中，有如下代码：
85行 nuscenes_converter.export_2d_annotation(root_path, info_train_path, version=version)
请问在数据预处理时，是否将root_path也写进了文件里呢？

**Comment by GuWei007** [comment]
网速太慢，这2个文件能共享就比较好
nuscenes_infos_temporal_val.pkl
nuscenes_infos_temporal_train.pkl
