### ISSUE TITLE
Question about the htted points for each camera. 

### ISSUE THREAD

**Issue by Solacex** [zhiqi-li/BEVFormer#71]
Hello,

Thanks for your inspiring work and congrats on the acceptance of this work!

To obtain the hit region for each camera, the code employs the function get_reference_points and point sampling. 
For the point sampling function, I can understand the part before line 126, which performs multiplication between the pixel coordinates and the extrinsic of each camera. But I cannot get the reason the latter filtering, i.e., Line130-136. 

https://github.com/zhiqi-li/BEVFormer/blob/ef4dfe3f36ffdc0cd3cc47ed32c7fb42886704b7/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L133-L136

Can you give some hints or explanations for this?

**Comment by zhiqi-li** [comment]
When you project a point (x,y,z) in 3D space onto the 2D image plane, you get a projected point (a,b), but (a,b) may be outside the image. We need to judge whether the projection point is legal or not.

**Comment by Solacex** [comment]
Thanks for your prompt response, and it  really helps.
