### ISSUE TITLE
Checkpoint for BEVFormer-S 

### ISSUE THREAD

**Issue by Solacex** [zhiqi-li/BEVFormer#73]
Hello, 

Does the provided checkpoint, i.e., R101-DCN | BEVFormer-small | 24ep | 47.9 | 37.0 | 10500M, correspond to the BEVformer-S in Table 3 of the paper?

**Comment by zhiqi-li** [comment]
BEVFormer-small is a smaller version of our default BEVFormer, which requires less GPU memory. BEVFormer-S in the paper is the static version of BEVFormer.

**Comment by Solacex** [comment]
So will you consider providing the checkpoint of BEVFormer-S?
