### ISSUE TITLE
How to visualize the segmentation results

### ISSUE THREAD

**Issue by GRE-EXAMINATION** [zhiqi-li/BEVFormer#74]
Dear author @zhiqi-li ,

Thanks for the great work! please how should I visualize the segmentation results. I have noticed that "visualize_results.py" can visualize the results for 3D detection but not for segmentation part. Could you please give some advice?

Thanks a lot!

**Comment by zhiqi-li** [comment]
Hi, the segmentation code of bevformer is under preparing. We will release related codes later.

**Comment by akhil22** [comment]
Hi,
Is the segmentation code released ?
