### ISSUE TITLE
CAN_BUS Compared to ego_pose

### ISSUE THREAD

**Issue by ziqipang** [zhiqi-li/BEVFormer#75]
Hi, Thank you for the nice repo sharing your work!

I have a question regarding the `CAN_BUS` used in BEVFormer. I read through the code and it seems `CAN_BUS` information is only used for compensating for the ego-motion. Therefore, I am curious if you have tried using the `ego_pose` in the older versions of NuScenes, which are more widely used. Specifically, I wonder if using `ego_pose` can produce similar results or if you have any conclusions regarding this?

Thank you so much for your time and help!

**Comment by zhiqi-li** [comment]
Hi, we also embed `CAN_BUS` into high-dimensional embedding and add it to BEV queries.  
Actually, we use the `ego_pose` provided in nuScenes rather than the data in `CAN_BUS`. You can refer to this:
https://github.com/zhiqi-li/BEVFormer/blob/master/docs/can_bus.ipynb.

**Comment by ziqipang** [comment]
@zhiqi-li Thanks for the clarification! I will take a look.
