### ISSUE TITLE
How impactful is can_bus usage?

### ISSUE THREAD

**Issue by Divadi** [zhiqi-li/BEVFormer#78]
I find that the transformer queries incorporate ego can_bus information.
https://github.com/zhiqi-li/BEVFormer/blob/5a25c8b3b70956174b3c1876321967e265b2da42/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L158-L162
I was wondering how the performance changes without can_bus?

Thank you!

**Comment by zhiqi-li** [comment]
![image](https://user-images.githubusercontent.com/27915819/180783734-602a7366-f66e-455d-b554-e94f822e97c9.png)

**Comment by Qi-Zhangyang** [comment]
So the B means to disable the Temporal Self-Attention??
