### ISSUE TITLE
Some questions about the Spatial Cross-Attention

### ISSUE THREAD

**Issue by liqikai9** [zhiqi-li/BEVFormer#8]
Hi, thanks for your great work! 

In your paper, you mention that: **For one BEV query, the projected 2D points can only fall on some views, and other views are not hit.**
 How do you determine which views will the reference points fall on? 
And I am confused about the equation (4). What does the `zij · [xij yij 1]` mean? Is the `zij` a typo?

 Hopefully, you can offer some explanations. Thanks~

**Comment by zhiqi-li** [comment]
`zij · [xij yij 1]=[zij·xij, zij·yij, zij]`   (xij, yij) are the coordinates on the image plane.
