### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by CatOneTwo** [zhiqi-li/BEVFormer#80]
When you resize the input of the image in bevformer_tiny_fp16, how to make the equal change on ground truth 3D bounding boxes?

**Comment by zhiqi-li** [comment]
Hi, when the images being resized, the GT bboxes of  3D space  kept the same.

**Comment by CatOneTwo** [comment]
Hi, do you mean the 3D bounding boxes don't need to be changed?

**Comment by zhiqi-li** [comment]
3D bboxes don't need to be changed because we adapt the camera parameters.

**Comment by CatOneTwo** [comment]
Thank you, I got it~
