### ISSUE TITLE
Visualization Tools

### ISSUE THREAD

**Issue by ziqipang** [zhiqi-li/BEVFormer#83]
Hi, Thanks for the nice work!

I really like the demo video you have shown at the beginning of the README, especially how you project the bounding boxes onto images, even those crossing two images. Therefore, I am wondering if you may point me to some useful sources or kindly include this part in the repository?

Thank you so much!

**Comment by zhiqi-li** [comment]
I use this script to generate the visualization results https://github.com/zhiqi-li/BEVFormer/blob/master/tools/analysis_tools/visual.py. Since this script only generates image results, I also use other tools to generate the final demo video.

**Comment by ziqipang** [comment]
@zhiqi-li Thanks! I tried it out and the results look really impressive!

**Comment by zhangbo666666** [comment]
> 



> 我使用此脚本生成可视化结果https://github.com/zhiqi-li/BEVFormer/blob/master/tools/analysis_tools/visual.py。由于该脚本仅生成图像结果，因此我还使用其他工具来生成最终的演示视频。

Hello author, I am a graduate student at Harbin Institute of Technology and currently replicating your BEVFormer. May I ask if it is convenient to share the visualization tool used in your final demonstration video? Thank you very much!!! I will also cite your paper for future paper writing. Thank you and I hope to receive your reply.

**Comment by zhangbo666666** [comment]
> 

Hello author, I am a graduate student at Harbin Institute of Technology and currently studying your BEVFormer. May I ask, is it convenient to share the visualization tools used in your final demonstration video? Thank you. I will also cite your paper for future writing purposes. Thank you, I hope to receive your reply.

**Comment by zhangbo666666** [comment]
> I use this script to generate the visualization results https://github.com/zhiqi-li/BEVFormer/blob/master/tools/analysis_tools/visual.py. Since this script only generates image results, I also use other tools to generate the final demo video.

Hello author, I am a graduate student at Harbin Institute of Technology and currently studying your BEVFormer. May I ask, is it convenient to share the visualization tools used in your final demonstration video? Thank you. I will also cite your paper for future writing purposes. Thank you, I hope to receive your reply.

**Comment by zhangbo666666** [comment]
> @zhiqi-li Thanks! I tried it out and the results look really impressive!

Hello, brother. How did you create the visualization video？

**Comment by PannagaS** [comment]
Brother, what are the "other" visualization tools you used? Plzz help :)
