### ISSUE TITLE
About Backbone input shape

### ISSUE THREAD

**Issue by Han-lim** [zhiqi-li/BEVFormer#84]
I have a question about this interesting model.
I understood that the batch size is 1(i.e. 6 images).
so, I wonder if 6 multi-view images are used as input for the same backbone network.
if not, did you use different backbone weight for each view (6 resnet101 backbone for each location)?

**Comment by zhiqi-li** [comment]
For multi-view images, they are fed into a shared backbone.

**Comment by Han-lim** [comment]
Thank you for your response:)
