### ISSUE TITLE
cannot reproduce the result of BEVFormer-Base

### ISSUE THREAD

**Issue by Yaozh66** [zhiqi-li/BEVFormer#91]
Hi, thanks for your great work.
I want to reproduce the BEVFormer-Base version with default config and default pretrained model you have provided, with nothing else altered, buy only get 0.4111 NDS on val, which is far away from the reported 0.517. And results are listed as the below image. Any suggestion?

Thanks in advance!
![2022-08-09 15-30-44屏幕截图](https://user-images.githubusercontent.com/44368323/183590947-6d0feb8c-eced-4751-aba3-5fcb27857830.png)

**Comment by zhiqi-li** [comment]
Hi, I think you use mmdet3d>=1.0  to generate the annotation files， which has different coordinate system from mmdet3d<1.0. Please follow our instructions to install correct environments.

**Comment by Yaozh66** [comment]
Thank you very much! You help me a lot!

**Comment by Cathy0908** [comment]
if mmdet3d>=1.0, the diff is in api `mmdet3d.datasets.nuscenes_dataset.output_to_nusc_box`, remove the following line in the api:

```python
# our LiDAR coordinate system -> nuScenes box coordinate system
nus_box_dims = box_dims[:, [1, 0, 2]]
```

**Comment by simon1624** [comment]
我用的mmdet3d=0.17,但是NDS也只有0.41，以下是版本情况
mmcv-full                     1.4.0
mmdet                         2.14.0
mmdet3d                       0.17.1               
mmsegmentation                0.14.1

**Comment by simon1624** [comment]
![image](https://user-images.githubusercontent.com/56028524/219567543-1dfc7bcd-2076-4efa-a64f-db9e498b8e33.png)
