### ISSUE TITLE
single_gpu_test

### ISSUE THREAD

**Issue by kd12138888** [zhiqi-li/BEVFormer#92]
thanks for sharing code ,but when i  Eval BEVFormer with 1 GPUs :  

Traceback (most recent call last):
  File "./tools/test.py", line 268, in <module>
    main()
  File "./tools/test.py", line 232, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/bbblue/Downloads/mmdetection3d-master/mmdet3d/apis/test.py", line 48, in single_gpu_test
    model.module.show_results(
TypeError: show_results() got an unexpected keyword argument 'show'

**Comment by zhiqi-li** [comment]
Please use this commnad `./tools/dist_test.sh ./projects/configs/bevformer/bevformer_base.py ./path/to/ckpts.pth 1`

**Comment by kd12138888** [comment]
> Please use this commnad `./tools/dist_test.sh ./projects/configs/bevformer/bevformer_base.py ./path/to/ckpts.pth 1`

when i use this command ,there are two errors
1:TypeError: cannot pickle 'dict_keys' object
2:torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by zhiqi-li** [comment]
https://github.com/zhiqi-li/BEVFormer/issues/23#issuecomment-1165072537

**Comment by leonlee723** [comment]
https://github.com/zhiqi-li/BEVFormer/issues/23#issuecomment-1165072537 show 404!

**Comment by sainttelant** [comment]
@leonlee723 hello， did you solve the issues ? i have encountered the same issue with you, when i use a single 3090 to evaluate the mini datasets

**Comment by NiuMa-1234** [comment]
> [@leonlee723](https://github.com/leonlee723) hello， did you solve the issues ? i have encountered the same issue with you, when i use a single 3090 to evaluate the mini datasets

Hi, have you solved this problem? I encountered same error in testing the mini datasets on a single 4090
