### ISSUE TITLE
train one epoch eval. this is normal?

### ISSUE THREAD

**Issue by wang911205** [zhiqi-li/BEVFormer#93]
Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.000   1.337   0.314   1.481   0.482   0.112
truck   0.000   1.000   1.000   1.000   1.000   1.000
bus     0.000   1.000   1.000   1.000   1.000   1.000
trailer 0.000   1.000   1.000   1.000   1.000   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.003   1.271   0.621   1.842   0.718   0.811
motorcycle      0.000   1.000   1.000   1.000   1.000   1.000
bicycle 0.000   1.000   1.000   1.000   1.000   1.000
traffic_cone    0.000   1.000   1.000   nan     nan     nan
barrier 0.000   1.000   1.000   1.000   nan     nan

**Comment by zhiqi-li** [comment]
Sorry, this is not normal.

**Comment by wang911205** [comment]
> Sorry, this is not normal.
epoch 24 result. the problem may be cause by?

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.277   0.945   0.222   1.205   0.532   0.383
truck   0.166   0.983   0.468   1.698   0.474   0.323
bus     0.195   1.155   0.418   1.958   4.398   0.337
trailer 0.000   1.000   1.000   1.000   1.000   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.195   0.970   0.304   1.507   0.940   0.340
motorcycle      0.010   0.905   0.542   1.689   0.333   0.870
bicycle 0.000   0.968   0.795   1.120   4.632   0.533
traffic_cone    0.059   1.245   0.610   nan     nan     nan
barrier 0.000   1.000   1.000   1.000   nan     nan

**Comment by zhiqi-li** [comment]
I am sorry, I didn't notice that you use nuscenes-mini to train BEVFormer. Actually, the nuScenes-mini is too small to make the model converge. I recommnd you to use full nuscenes data. I think this result is normal if you use nuscenes-mini.

**Comment by wang911205** [comment]
> 

OK，Thanks.
